src/habranalog/accsapp/urls.py
from django.urls import path
from accsapp.views import *


app_name='accsapp'
urlpatterns=[
    path('sign-up',signup,name='signup'),
    path('sign-in',signin,name='signin'),
    path('sign-out',signout,name='signout'),
    path('profile/', profile, name='profile'),
]

src/habranalog/articleapp/urls.py
from django.urls import path
from articleapp.views import *


app_name='articleapp'
urlpatterns=[
    path('',home,name='home'),
    path('view-art-<int:art_id>',view_art,name='view_art'),
    path('create-article/',create_article, name='create_article'),
    path('change-article-<int:art_id>',change_article, name='change_article'),
    path('view-article-<int:art_id>',view_article,name='view_article'),
    path('delete-article-<int:art_id>',delete_article,name='delete_article'),

]

src/habranalog/habranalog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('articleapp.urls')),
    path('accs/',include('accsapp.urls')),
    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/habranalog/accsapp/models.py
from django.db import models

# Create your models here.

src/habranalog/articleapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title=models.CharField(max_length=150)
    prememo=models.TextField(null=True,blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='articleapp/images',null=True,blank=True)
    data_published=models.DateField(auto_now_add=True)
    published=models.BooleanField(default=False)
    def __str__(self):
        return str(self.id)+'__'+self.title
    
class ArticlesBlock(models.Model):
    title=models.CharField(max_length=150)
    prememo=models.TextField(null=True,blank=True)
    image=models.ImageField(upload_to='articleapp/images',null=True,blank=True)
    data_published=models.DateField(auto_now_add=True)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)+'__'+self.title   
    
class Views(models.Model):
    user=models.ForeignKey(User,on_delete=models.PROTECT)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)
    class Meta:
        unique_together=('user','article',)
    

    

src/habranalog/mainapp/models.py
from django.db import models

# Create your models here.

src/habranalog/articleapp/forms.py
from articleapp.models import *
from django.forms import ModelForm

class CreateArticleForm(ModelForm):
    class Meta:
        model=Article
        fields=['title','prememo','image']

src/habranalog/accsapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from articleapp.models import *

# Create your views here.

def signup(request):
    if request.method=='GET':
        return render(request,'accsapp/signup.html',{'form':UserCreationForm()})
    else:
        if request.POST['password1']==request.POST['password2']:
            try:
                user=User.objects.create_user(username=request.POST['username'],password=request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('articleapp:home')
            except IntegrityError:
                return render(request,'accsapp/signup.html',{'form':UserCreationForm(),'error':'Такой пользователь уже существует'})
        else:
            return render(request,'accsapp/signup.html',{'form':UserCreationForm(),'error':'Пароли не совпадают'})

def signin(request):
    if request.user.is_authenticated:
        return redirect('articleapp:home')
    else:
        if request.method=='GET':
            return render(request,'accsapp/signin.html',{'form':AuthenticationForm()})
        else:
            user=authenticate(request,username=request.POST['username'],password=request.POST['password'])
            if user is None:
                return render(request,'accsapp/signin.html',{'form':AuthenticationForm(),'error':'Такого пользователя не существует'})
            else:
                login(request,user)
                return redirect('articleapp:home')
@login_required
def signout(request):
    logout(request)
    return redirect('articleapp:home')

@login_required
def profile(request):
    publicart=Article.objects.filter(author=request.user, published=True)
    privateart=Article.objects.filter(author=request.user, published=False)
    return render(request, 'accsapp/profile.html',context={'publicart':publicart,'privateart':privateart})

src/habranalog/articleapp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from articleapp.models import *
from django.contrib.auth.decorators import login_required
from articleapp.forms import *

# Create your views here.

def home(request):
    data=Article.objects.filter(published=True)
    return render(request,'articleapp/home.html',{'articles':data})

def view_art(request,art_id):
    # if request.user.has_perm('articleapp.can_read_article'):
        viewscount=Views.objects.filter(article=art_id).count()
        data=get_object_or_404(Article,pk=art_id,published=True)
        try:
            v=Views.objects.create(user=request.user,article=data)
        except:
            pass
        blocks=ArticlesBlock.objects.filter(article=art_id)
        return render(request,'articleapp/view_art.html',{'article':data, 'blocks':blocks,'viewscount':viewscount})
    # else:
    #     return 

@login_required
def create_article(request):
    if request.method=='GET':
        return render(request,'articleapp/create_article.html',{'form':CreateArticleForm()})
    else:
        try:
            form=CreateArticleForm(request.POST,request.FILES)
            newart=form.save(commit=False)
            newart.author=request.user
            form.save()
            return redirect('articleapp:home')
        except:
            return render(request,'articleapp/create_article.html',{'form':CreateArticleForm(),'error':'некорректное значение'})

@login_required
def change_article(request,art_id):
    article=get_object_or_404(Article,pk=art_id,author=request.user)
    if request.method=='GET':
        return render(request,'articleapp/change_article.html',{'article':article})
    else:
        try:
            form=CreateArticleForm(request.POST,request.FILES,instance=article)
            form.save()
            return redirect('articleapp:home')
        except:
            return render(request,'articleapp/change_article.html',{'article':article,'error':'некорректное значение'})
        
@login_required
def view_article(request,art_id):
    article_=get_object_or_404(Article,pk=art_id,author=request.user)
    articleblocks=ArticlesBlock.objects.filter(article=art_id)
    return render(request,'articleapp/view_article.html',{'article':article_,'articleblocks':articleblocks})

@login_required
def delete_article(request,art_id):
    article=get_object_or_404(Article,pk=art_id,author=request.user)
    if request.method=='POST':
        article.delete()
        return redirect('articleapp:home')

src/habranalog/mainapp/views.py
from django.shortcuts import render

# Create your views here.

src/habranalog/accsapp/templates/accsapp/profile.html
{% extends 'mainapp/base.html' %}
{% block content %}

<h2>Мой профиль</h2>

<h2>Мои статьи</h2>

<h3>Опубликованные</h3>
{% for i in publicart %}
<div class="card w-50">
    <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>

        <a href="{% url 'articleapp:view_article' i.id %}" class="btn btn-primary">Редактировать</a>

    </div>
</div>
<br>
{% endfor %}

<h3>Неопубликованные</h3>
{% for j in privateart %}
<div class="card w-50">
    <div class="card-body">
        <h5 class="card-title">{{ j.title }}</h5>

        <a href="{% url 'articleapp:view_article' j.id %}" class="btn btn-primary">Редактировать</a>

    </div>
</div>
<br>
{% endfor %}

{% endblock %}

src/habranalog/accsapp/templates/accsapp/signin.html
<form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Войти">
</form>
<small>{ error }</small>

src/habranalog/accsapp/templates/accsapp/signup.html
<form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегестрироваться">
</form>
<small>{ error }</small>

src/habranalog/articleapp/templates/articleapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HabrAnalog</title>
</head>
<body>
    {% block content %}


    {% end block %}
</body>
</html>

src/habranalog/articleapp/templates/articleapp/change_article.html
    
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}    
    <p>
        <label for="id_title">Title:</label>
        <input type="text" name="title" maxlength="150" required id="id_title" value="{{ article.title }}">
    
    
  </p>

  
  <p>
    <label for="id_prememo">Prememo:</label>
    <textarea name="prememo" cols="40" rows="10" id="id_prememo">
        {{ article.prememo }}
</textarea>
    
    
  </p>

  
  <p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" accept="image/*" id="id_image">
    
    
      
    
  </p>
    <input type="submit" value="Изменить">
</form>
<form action="{% url 'articleapp:delete_article' article.id %}" method="POST">
    {% csrf_token %}    
    <input type="submit" value="Удалить">
</form>
<small> {{ error }}</small>

src/habranalog/articleapp/templates/articleapp/create_article.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать">
</form>
<small> {{ error }}</small>

src/habranalog/articleapp/templates/articleapp/home.html
{% extends 'mainapp/base.html' %}
{% block content %}

<form action="" method="get">
    <select name="sort_by" id="">
        <option value="up" {% if user_filter_state == 'up' %} selected {% endif %}>По возрастанию</option>
        <option value="down" {% if user_filter_state == 'down' %} selected {% endif %}>По убыванию</option>
    </select>
<input type="submit" name="Сортировать" id="">
</form>

{% autoescape off %}
    <div class="container">
    {% for i in articles %}
    <h2>
        <a href="{% url 'articleapp:view_art' i.id %}">
            {{ i.title }}
        </a>
    </h2>
    <h3>
        {{ i.prememo }}
    </h3>
    {% if i.image %}
    <img src="  {{ i.image.url }} " alt="" >
    </div>

    {% endif %}
    {% endfor %}
    {% endautoescape %}
{% endblock %}

src/habranalog/articleapp/templates/articleapp/view_art.html
{% extends 'mainapp/base.html' %}
{% block content %}

<h2>{{ article.title }}</h2>
{% for i in blocks %}
<h3>{{ i.title }}</h3>
{% endfor %}

<h2> {{ viewscount }}</h2>

{% endblock %}

src/habranalog/articleapp/templates/articleapp/view_article.html
{% extends 'mainapp/base.html' %}
{% block content %}


<h3>Статья</h3>
<div class="card w-50">
    <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>

        <a href="{% url 'articleapp:change_article' article.id %}" class="btn btn-primary">Редактировать</a>

    </div>
</div>
<br>

<h3>Блоки</h3>
{% for j in articlebclocks %}
<div class="card w-50">
    <div class="card-body">
        <h5 class="card-title">{{ j.title }}</h5>

        <a href="#" class="btn btn-primary">Редактировать</a>

    </div>
</div>
<br>
{% endfor %}


{% endblock %}

src/habranalog/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habranalog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="#">HabrAnalog</a>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'articleapp:home' %}">Главная<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articleapp:create_article' %}">Добавить</a>
            </li>
          </ul>
          
            {% if user.is_authenticated %}
            
            {{ user.username }}  
             
            <form class="form-inline my-2 my-lg-0" action="{% url 'accsapp:signout' %}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Выйти</button>
            </form>
            {% else %}
            <a class="nav-link" href="{% url 'accsapp:signin' %}">Войти</a>
            <a class="nav-link" href="{% url 'accsapp:signup' %}">Зарегестрироваться</a>
            {% endif %}
        </div>
        </div>
      </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>